FROM python:alpine3.10

WORKDIR /geo

COPY .env .env

COPY ./src .

RUN apk update  \
    && apk upgrade  \
    && pip install --upgrade pip  \
    && pip3 install -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
